@NewNet8Auth_HostAddress = http://localhost:5280

GET {{NewNet8Auth_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{NewNet8Auth_HostAddress}}/login/
Content-Type: application/json
Accept: application/json

{
  "email": "a@a.com",
  "password": "12345aA!"
}

###